---
- name: Ensure unattended-upgrades are installed
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Copy unattended-upgrades configuration files to destination
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades

- name: Ensure that the unattended-upgrades is enabled and running
  ansible.builtin.service:
    name: unattended-upgrades
    enabled: true
    state: started
